sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t biodemo2 .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /biodemo2/.travis/unit-test.sh biodemo2
  # Unit tests
  - docker run --entrypoint /biodemo2/functional_tests/biodemo2-test.sh biodemo2 -p biodemo2 -d /biodemo2/functional_tests/test_data -v

  # CWL definition test
  - cwltool biodemo2.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
